import * as React from 'react';
import { Activity, AlertTriangle, DollarSign, ShoppingCart, TrendingUp, Wallet, Search, Plus, Pencil, Package, History, Target, BrainCircuit, Scale, SlidersHorizontal, ShieldCheck, CheckCircle2, Clock3, ListChecks, ReceiptText, WalletCards, ArrowUpDown, Brain, LineChart, BarChart3, Megaphone, ShoppingBag, Award, Boxes, Users, X, Calculator, LayoutDashboard } from 'lucide-react';
import type { SaleRecord, Expense, Receivable, Payable, CashClosure, CashMovement } from '../domain/types';
import { saveJson } from '../utils/storage';
const localDateKey = (d = new Date()) => { const y=d.getFullYear(); const m=String(d.getMonth()+1).padStart(2,'0'); const day=String(d.getDate()).padStart(2,'0'); return y+'-'+m+'-'+day; };
const currentMonthKey = (d = new Date()) => localDateKey(d).slice(0,7);
const isCurrentMonth = (date:string) => (date||'').slice(0,7) === currentMonthKey();

import { sumSales, sumProfit, sumExpenses, pendingReceivables, pendingPayables, cashSales, collectedReceivables, supplierPayments, calculateCashFlow, calculateExpectedCash, createCashClosure, addCashMovement } from '../services/financeService';

const money = (value: number) => new Intl.NumberFormat('es-HN', { style: 'currency', currency: 'HNL', maximumFractionDigits: 2 }).format(value);

export function Finance({sales,expenses,setExpenses,receivables,setReceivables,payables,setPayables}:{sales:SaleRecord[];expenses:Expense[];setExpenses:(e:Expense[])=>void;receivables:Receivable[];setReceivables:(e:Receivable[])=>void;payables:Payable[];setPayables:(e:Payable[])=>void}) {
  const [description,setDescription]=useState(''); const [amount,setAmount]=useState(0); const [category,setCategory]=useState('Operación');
  const [paymentAmount,setPaymentAmount]=useState<Record<number,number>>({});
  const [opening,setOpening]=useState(0); const [counted,setCounted]=useState(0); const [note,setNote]=useState('');
  const [closures,setClosures]=useState<CashClosure[]>(()=>{try{const s=localStorage.getItem('difarmas_cash_closures');return s?JSON.parse(s):[]}catch{return []}});
  const [movements,setMovements]=useState<CashMovement[]>(()=>{try{const s=localStorage.getItem('difarmas_cash_movements');return s?JSON.parse(s):[]}catch{return []}});
  useEffect(()=>{localStorage.setItem('difarmas_cash_closures',JSON.stringify(closures))},[closures]);
  useEffect(()=>{localStorage.setItem('difarmas_cash_movements',JSON.stringify(movements))},[movements]);
  const salesTotal=sumSales(sales); const profit=sumProfit(sales); const expenseTotal=sumExpenses(expenses);
  const receivablePending=pendingReceivables(receivables); const payablePending=pendingPayables(payables);
  const cashSalesTotal=cashSales(sales); const collected=collectedReceivables(receivables); const supplierPaymentsTotal=supplierPayments(payables);
  const cashFlow=calculateCashFlow(sales,receivables,expenses,payables);
  const today=new Date().toISOString().slice(0,10);
  const dayMovementIn=movements.filter(m=>m.date.slice(0,10)===today&&m.type==='Entrada').reduce((a,m)=>a+m.amount,0); const dayMovementOut=movements.filter(m=>m.date.slice(0,10)===today&&m.type==='Salida').reduce((a,m)=>a+m.amount,0);
  const daySales=sales.filter(s=>s.date.slice(0,10)===today&&s.payment!=='Crédito').reduce((a,s)=>a+s.total,0);
  const dayCollections=receivables.filter(r=>r.lastPaymentDate?.slice(0,10)===today).reduce((a,r)=>a+r.paid,0);
  const dayExpenses=expenses.filter(e=>e.date.slice(0,10)===today).reduce((a,e)=>a+e.amount,0);
  const daySupplierPayments=payables.filter(r=>r.lastPaymentDate?.slice(0,10)===today).reduce((a,r)=>a+r.paid,0);
  const expected=calculateExpectedCash(opening,daySales,dayCollections,dayMovementIn,dayExpenses,daySupplierPayments,dayMovementOut);
  const addExpense=()=>{if(!description.trim()||amount<=0)return;setExpenses([...expenses,{id:Date.now(),description,amount,category,date:new Date().toISOString()}]);setDescription('');setAmount(0);};
  const collect=(r:Receivable)=>{const value=Math.min(paymentAmount[r.id]||0,Math.max(0,r.total-r.paid));if(value<=0)return;setReceivables(receivables.map(x=>x.id===r.id?{...x,paid:x.paid+value,lastPaymentDate:new Date().toISOString()}:x));setPaymentAmount({...paymentAmount,[r.id]:0});};
  const paySupplier=(r:Payable)=>{const value=Math.min(paymentAmount[r.id]||0,Math.max(0,r.total-r.paid));if(value<=0)return;setPayables(payables.map(x=>x.id===r.id?{...x,paid:x.paid+value}:x));setPaymentAmount({...paymentAmount,[r.id]:0});};
  const closeCash=()=>{setClosures([createCashClosure(opening,daySales,dayCollections,dayExpenses,daySupplierPayments,expected,counted,note),...closures]);setOpening(counted);setCounted(0);setNote('');};
  return <div className="content"><div className="page-head"><div><span className="pill">MVP · FINANZAS + CAJA</span><h2>Finanzas y caja</h2><p>Control de ventas, cobros, pagos, flujo de caja y cierre diario.</p></div></div>
  <div className="grid metrics"><article className="card metric"><div className="metric-top"><span>Ventas</span><ShoppingCart size={20}/></div><strong>{money(salesTotal)}</strong><small>{sales.length} operaciones</small></article><article className="card metric"><div className="metric-top"><span>Utilidad bruta</span><TrendingUp size={20}/></div><strong>{money(profit)}</strong></article><article className="card metric"><div className="metric-top"><span>Por cobrar</span><DollarSign size={20}/></div><strong>{money(receivablePending)}</strong></article><article className="card metric"><div className="metric-top"><span>Por pagar</span><Wallet size={20}/></div><strong>{money(payablePending)}</strong></article></div>
  <div className="grid metrics"><article className="card metric"><div className="metric-top"><span>Flujo de caja</span><Activity size={20}/></div><strong>{money(cashFlow)}</strong><small>Entradas de efectivo − egresos</small></article><article className="card metric"><div className="metric-top"><span>Ventas contado</span><DollarSign size={20}/></div><strong>{money(cashSalesTotal)}</strong></article><article className="card metric"><div className="metric-top"><span>Cobros</span><DollarSign size={20}/></div><strong>{money(collected)}</strong></article><article className="card metric"><div className="metric-top"><span>Pagos proveedores</span><Wallet size={20}/></div><strong>{money(supplierPaymentsTotal)}</strong></article></div>
  <div className="finance-grid"><section className="card"><div className="card-title"><div><h3>Registrar gasto</h3><p>Alquiler, servicios, personal, impuestos u otros.</p></div><Wallet size={20}/></div><div className="expense-form"><input value={description} onChange={e=>setDescription(e.target.value)} placeholder="Descripción del gasto"/><input type="number" min="0" value={amount||''} onChange={e=>setAmount(Number(e.target.value))} placeholder="Monto"/><select value={category} onChange={e=>setCategory(e.target.value)}><option>Operación</option><option>Alquiler</option><option>Servicios</option><option>Personal</option><option>Impuestos</option><option>Otros</option></select><button className="primary" onClick={addExpense}>Registrar gasto</button></div></section>
  <section className="card"><div className="card-title"><div><h3>Últimos gastos</h3><p>Control de egresos</p></div></div>{expenses.length===0?<div className="cart-empty">Todavía no hay gastos.</div>:expenses.slice(-8).reverse().map(e=><div className="expense-row" key={e.id}><div><strong>{e.description}</strong><small>{e.category}</small></div><strong>{money(e.amount)}</strong></div>)}</section></div>
  <div className="card table-wrap finance-table"><div className="card-title"><div><h3>Ventas registradas</h3><p>Historial del POS</p></div></div>{sales.length===0?<div className="cart-empty">No hay ventas.</div>:<table><thead><tr><th>Fecha</th><th>Cliente</th><th>Pago</th><th>Total</th><th>Utilidad</th></tr></thead><tbody>{sales.slice().reverse().map(x=><tr key={x.id}><td>{new Date(x.date).toLocaleString('es-HN')}</td><td>{x.customer||'Contado'}</td><td>{x.payment}</td><td>{money(x.total)}</td><td>{money(x.profit)}</td></tr>)}</tbody></table>}</div>
  <div className="finance-grid"><section className="card"><div className="card-title"><div><h3>Cuentas por cobrar</h3><p>Registra abonos de clientes.</p></div></div>{receivables.length===0?<div className="cart-empty">No hay cuentas por cobrar.</div>:receivables.slice().reverse().map(r=>{const balance=Math.max(0,r.total-r.paid);return <div className="expense-row" key={r.id}><div><strong>{r.customer}</strong><small>Saldo {money(balance)} · Vence {new Date(r.dueDate+'T00:00:00').toLocaleDateString('es-HN')}</small></div>{balance>0&&<div className="qty"><input type="number" min="0" max={balance} value={paymentAmount[r.id]||''} onChange={e=>setPaymentAmount({...paymentAmount,[r.id]:Number(e.target.value)})}/><button onClick={()=>collect(r)}>Cobrar</button></div>}</div>})}</section>
  <section className="card"><div className="card-title"><div><h3>Cuentas por pagar</h3><p>Registra pagos a proveedores.</p></div></div>{payables.length===0?<div className="cart-empty">No hay cuentas por pagar.</div>:payables.slice().reverse().map(r=>{const balance=Math.max(0,r.total-r.paid);return <div className="expense-row" key={r.id}><div><strong>{r.supplier}</strong><small>Saldo {money(balance)} · Vence {new Date(r.dueDate+'T00:00:00').toLocaleDateString('es-HN')}</small></div>{balance>0&&<div className="qty"><input type="number" min="0" max={balance} value={paymentAmount[r.id]||''} onChange={e=>setPaymentAmount({...paymentAmount,[r.id]:Number(e.target.value)})}/><button onClick={()=>paySupplier(r)}>Pagar</button></div>}</div>})}</section></div>
  <section className="card"><div className="card-title"><div><h3>Movimientos de caja</h3><p>Entradas y salidas manuales que afectan el efectivo.</p></div><Activity size={20}/></div><div className="expense-form"><select id="cashType"><option>Entrada</option><option>Salida</option></select><input id="cashDesc" placeholder="Descripción"/><input id="cashAmount" type="number" min="0" placeholder="Monto"/><select id="cashCat"><option>Otros</option><option>Aporte</option><option>Retiro</option><option>Préstamo</option><option>Devolución</option><option>Banco</option></select><button className="primary" onClick={()=>{const t=(document.getElementById('cashType') as HTMLSelectElement).value as 'Entrada'|'Salida';const d=(document.getElementById('cashDesc') as HTMLInputElement).value.trim();const a=Number((document.getElementById('cashAmount') as HTMLInputElement).value);const cat=(document.getElementById('cashCat') as HTMLSelectElement).value;if(!d||a<=0)return;setMovements([addCashMovement(t,d,a,cat),...movements]);}}>Registrar</button></div>{movements.slice(0,8).map(m=><div className="expense-row" key={m.id}><div><strong>{m.description}</strong><small>{m.type} · {m.category} · {new Date(m.date).toLocaleDateString('es-HN')}</small></div><strong>{m.type==='Entrada'?'+':'-'}{money(m.amount)}</strong></div>)}</section>
  <section className="card"><div className="card-title"><div><h3>Cierre de caja diario</h3><p>Calcula cuánto debería haber en efectivo y compara con el efectivo contado.</p></div><Wallet size={20}/></div><div className="expense-form"><label>Saldo inicial<input type="number" min="0" value={opening||''} onChange={e=>setOpening(Number(e.target.value))}/></label><div className="summary-line"><span>Ventas de contado hoy</span><strong>{money(daySales)}</strong></div><div className="summary-line"><span>Cobros de hoy</span><strong>{money(dayCollections)}</strong></div><div className="summary-line"><span>Gastos de hoy</span><strong>{money(dayExpenses)}</strong></div><div className="summary-line"><span>Pagos a proveedores hoy</span><strong>{money(daySupplierPayments)}</strong></div><div className="grand"><span>Efectivo esperado</span><strong>{money(expected)}</strong></div><label>Dinero contado<input type="number" min="0" value={counted||''} onChange={e=>setCounted(Number(e.target.value))}/></label><label>Nota<input value={note} onChange={e=>setNote(e.target.value)} placeholder="Observación del cierre"/></label><button className="primary" onClick={closeCash}>Cerrar caja</button></div></section>
  <section className="card"><div className="card-title"><div><h3>Historial de cierres</h3><p>Diferencias encontradas por día.</p></div></div>{closures.length===0?<div className="cart-empty">Aún no hay cierres.</div>:closures.slice(0,10).map(x=><div className="expense-row" key={x.id}><div><strong>{new Date(x.date).toLocaleDateString('es-HN')}</strong><small>Esperado {money(x.expected)} · Contado {money(x.counted)}{x.note?' · '+x.note:''}</small></div><strong>{x.difference>=0?'+':''}{money(x.difference)}</strong></div>)}</section>
  </div>;
}
