import { ShoppingCart } from 'lucide-react';
import type { PurchaseItem, Product } from '../domain/types';
const money = (value: number) => new Intl.NumberFormat('es-HN', { style: 'currency', currency: 'HNL', maximumFractionDigits: 2 }).format(value);

export function Purchases({products,cart,setCart,search,setSearch,supplier,setSupplier,onReceive}:{products:Product[];cart:PurchaseItem[];setCart:(c:PurchaseItem[])=>void;search:string;setSearch:(v:string)=>void;supplier:string;setSupplier:(v:string)=>void;onReceive:(items:PurchaseItem[],paymentMethod:'Efectivo'|'Transferencia'|'Crédito',dueDate:string)=>void}) {
  const results=products.filter(p=>[p.code,p.name].join(' ').toLowerCase().includes(search.toLowerCase())).slice(0,6);
  const total=cart.reduce((sum,i)=>sum+i.unitCost*i.qty,0);
  const [paymentMethod,setPaymentMethod]=useState<'Efectivo'|'Transferencia'|'Crédito'>('Efectivo');
  const [dueDate,setDueDate]=useState(()=>{const d=new Date();d.setDate(d.getDate()+30);return d.toISOString().slice(0,10);});
  const add=(p:Product)=>{setCart(cart.some(i=>i.id===p.id)?cart.map(i=>i.id===p.id?{...i,qty:i.qty+1}:i):[...cart,{...p,qty:1,unitCost:p.cost}]);setSearch('');};
  const change=(id:number,delta:number)=>setCart(cart.map(i=>i.id===id?{...i,qty:Math.max(1,i.qty+delta)}:i));
  const updateCost=(id:number,value:number)=>setCart(cart.map(i=>i.id===id?{...i,unitCost:value}:i));
  return <div className="content"><div className="page-head"><div><span className="pill">MVP · MÓDULO 4</span><h2>Compras y recepción</h2><p>Registra compras, costos y entrada de mercancía al inventario.</p></div></div>
  <div className="purchase-grid"><section><div className="card purchase-head"><label>Proveedor<input value={supplier} onChange={e=>setSupplier(e.target.value)} placeholder="Nombre del proveedor"/></label><div className="search"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar producto para agregar..." /></div></div>{search&&<div className="results card">{results.map(p=><button key={p.id} onClick={()=>add(p)}><span><strong>{p.name}</strong><small>{p.code} · Costo actual {money(p.cost)}</small></span><b>Agregar</b></button>)}</div>}<div className="card cart-card"><div className="card-title"><div><h3>Detalle de compra</h3><p>{cart.length} productos</p></div><Boxes size={20}/></div>{cart.length===0?<div className="cart-empty">Agrega productos a la compra.</div>:cart.map(i=><div className="purchase-row" key={i.id}><div><strong>{i.name}</strong><small>{i.code}</small></div><input type="number" min="0.01" value={i.unitCost} onChange={e=>updateCost(i.id,Number(e.target.value))}/><div className="qty"><button onClick={()=>change(i.id,-1)}>-</button><b>{i.qty}</b><button onClick={()=>change(i.id,1)}>+</button></div><strong>{money(i.unitCost*i.qty)}</strong></div>)}</div></section><aside className="card checkout"><h3>Recepción</h3><div className="summary-line"><span>Subtotal compra</span><strong>{money(total)}</strong></div><div className="summary-line"><span>Productos</span><strong>{cart.reduce((s,i)=>s+i.qty,0)}</strong></div><label className="checkout-label">Método de pago<select value={paymentMethod} onChange={e=>setPaymentMethod(e.target.value as typeof paymentMethod)}><option>Efectivo</option><option>Transferencia</option><option>Crédito</option></select></label>{paymentMethod==='Crédito'&&<label className="checkout-label">Vencimiento<input type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)}/></label>}<div className="grand"><span>Total</span><strong>{money(total)}</strong></div><button className="primary checkout-btn" disabled={!cart.length||!supplier.trim()} onClick={()=>{onReceive(cart,paymentMethod,dueDate);setCart([]);setSupplier('');setPaymentMethod('Efectivo');}}>Recibir mercancía</button><small className="helper">Al recibir, se suma al stock y se actualiza el costo del producto.</small></aside></div></div>;
}

